language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 5.3
          env: deps=low
        - php: 5.6
          env: deps=high
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
    - phpunit --coverage-clover=coverage.clover

notifications:
    email:
        recipients:
            - ci@verylastroom.comguillaume.morel@gmx.com
        on_success: change
        on_failure: change

