parameters:

services:
# Manager
    acme.demo.state.manager:
        class: Acme\DemoBundle\State\StateManager
        arguments: []

# State
    acme.demo.state.incomplete:
        class: Acme\DemoBundle\State\Implementation\StateIncomplete
        arguments: []
        tags:
            -  { name: acme.demo.default.state }
    acme.demo.state.waiting_payment:
        class: Acme\DemoBundle\State\Implementation\StateWaitingPayment
        arguments: []
        tags:
            -  { name: facme.demo.default.state }
    acme.demo.state.paid:
        class: Acme\DemoBundle\State\Implementation\StatePaid
        arguments: []
        tags:
            -  { name: acme.demo.default.state }
    acme.demo.state.cancelled:
        class: Acme\DemoBundle\State\Implementation\StateCancelled
        arguments: []
        tags:
            -  { name: acme.demo.default.state }
    acme.demo.state.to_delete:
        class: Acme\DemoBundle\State\Implementation\StateToDelete
        arguments: []
        tags:
            -  { name: acme.demo.default.state }
